useDotenv: true
service: demo-data-residency-api
frameworkVersion: '3'

plugins:
#  - serverless-plugin-warmup

custom:
  warmup:
    officeHoursWarmer:
      roleName: demo-data-residency-api-dev-${env:AWS_REGION,opt:region}-warmer
      enabled: true
      events:
        - schedule: cron(0/1 0-23 ? * MON-SUN *)
      concurrency: 6
      verbose: false
      logRetentionInDays: 7

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeAsync
            - lambda:InvokeFunction
          Resource: '*'

# https://gist.github.com/sdomagala/a647a69f0dd87af545d7c45dfc7b0114
resources:
  Resources:
    IamRoleLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - sqs.amazonaws.com
                  - lambda.amazonaws.com
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole

functions:
  api:
    handler: v1/index.handler
    memorySize: 256
    timeout: 120
    provisionedConcurrency: 3
    events:
      - http:
          cors: true
          path: /
          method: GET
  gallery:
    handler: v1/gallery.handler
    memorySize: 256
    timeout: 120
    provisionedConcurrency: 3
    events:
      - http:
          cors: true
          path: /gallery
          method: GET
  user:
    handler: v1/user.handler
    memorySize: 256
    timeout: 120
    provisionedConcurrency: 3
    events:
      - http:
          cors: true
          path: /user
          method: POST
  artlocal:
    handler: v1/artlocal.handler
    memorySize: 256
    timeout: 120
    provisionedConcurrency: 3
    events:
      - http:
          cors: true
          path: /artlocal
          method: POST
  artglobal:
    handler: v1/artglobal.handler
    memorySize: 256
    timeout: 120
    provisionedConcurrency: 3
    events:
      - http:
          cors: true
          path: /artglobal
          method: POST
  artuser:
    handler: v1/artuser.handler
    memorySize: 256
    timeout: 120
    provisionedConcurrency: 3
    events:
      - http:
          cors: true
          path: /artuser
          method: POST
